// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enchhbvettmnhbncuxiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVuY2hoYnZldHRtbmhibmN1eGl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNDYxMTQsImV4cCI6MjA3MTcyMjExNH0.zESb7h_JRvzOgf6KxcEpMbu94U6BNBx_L_hE1Jbx36Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});